### appspec.yml ####
version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/hello
hooks:
  BeforeInstall:
    - location: ./before.sh
      timeout: 120
      runas: root
  AfterInstall:
    - location: ./after.sh
      timeout: 120
      runas: root
